/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'id' : string,
  'model' : string,
  'nickname' : string,
  'make' : string,
  'createdAt' : bigint,
  'year' : bigint,
  'notes' : string,
}
export interface ChecklistItem {
  'id' : string,
  'eventId' : string,
  'checked' : boolean,
  'name' : string,
  'notes' : string,
  'category' : string,
}
export interface Event {
  'id' : string,
  'carId' : string,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'notes' : string,
  'location' : string,
  'eventType' : string,
}
export interface LapNote {
  'id' : string,
  'eventId' : string,
  'lapTime' : string,
  'sessionName' : string,
  'notes' : string,
  'timestamp' : bigint,
  'lapNumber' : bigint,
}
export interface TireLogSession {
  'id' : string,
  'targetPsiMax' : number,
  'targetPsiMin' : number,
  'flPsi' : number,
  'frPsi' : number,
  'eventId' : string,
  'sessionName' : string,
  'flTemp' : number,
  'rrTemp' : number,
  'tempUnit' : string,
  'frTemp' : number,
  'timestamp' : bigint,
  'rlPsi' : number,
  'rrPsi' : number,
  'rlTemp' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WearEntry {
  'id' : string,
  'carId' : string,
  'percentRemaining' : number,
  'installDate' : string,
  'updatedAt' : bigint,
  'treadDepthMm' : number,
  'notes' : string,
  'wearType' : string,
  'brand' : string,
  'position' : string,
  'lastChangedDate' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCar' : ActorMethod<[Car], undefined>,
  'createChecklistItem' : ActorMethod<[ChecklistItem], undefined>,
  'createEvent' : ActorMethod<[Event], undefined>,
  'createLapNote' : ActorMethod<[LapNote], undefined>,
  'createTireLogSession' : ActorMethod<[TireLogSession], undefined>,
  'createWearEntry' : ActorMethod<[WearEntry], undefined>,
  'deleteCar' : ActorMethod<[string], undefined>,
  'deleteChecklistItem' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteLapNote' : ActorMethod<[string], undefined>,
  'deleteTireLogSession' : ActorMethod<[string], undefined>,
  'deleteWearEntry' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCars' : ActorMethod<[], Array<Car>>,
  'getChecklistItemsForEvent' : ActorMethod<[string], Array<ChecklistItem>>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getLapNotesForEvent' : ActorMethod<[string], Array<LapNote>>,
  'getTireLogSessionsForEvent' : ActorMethod<[string], Array<TireLogSession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWearEntriesForCar' : ActorMethod<[string], Array<WearEntry>>,
  'initDefaultChecklist' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleChecklistItem' : ActorMethod<[string], undefined>,
  'updateCar' : ActorMethod<[Car], undefined>,
  'updateChecklistItem' : ActorMethod<[ChecklistItem], undefined>,
  'updateEvent' : ActorMethod<[Event], undefined>,
  'updateLapNote' : ActorMethod<[LapNote], undefined>,
  'updateTireLogSession' : ActorMethod<[TireLogSession], undefined>,
  'updateWearEntry' : ActorMethod<[WearEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];