/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Car = IDL.Record({
  'id' : IDL.Text,
  'model' : IDL.Text,
  'nickname' : IDL.Text,
  'make' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'notes' : IDL.Text,
});
export const ChecklistItem = IDL.Record({
  'id' : IDL.Text,
  'eventId' : IDL.Text,
  'checked' : IDL.Bool,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'category' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'carId' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'location' : IDL.Text,
  'eventType' : IDL.Text,
});
export const LapNote = IDL.Record({
  'id' : IDL.Text,
  'eventId' : IDL.Text,
  'lapTime' : IDL.Text,
  'sessionName' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'lapNumber' : IDL.Nat,
});
export const TireLogSession = IDL.Record({
  'id' : IDL.Text,
  'targetPsiMax' : IDL.Float64,
  'targetPsiMin' : IDL.Float64,
  'flPsi' : IDL.Float64,
  'frPsi' : IDL.Float64,
  'eventId' : IDL.Text,
  'sessionName' : IDL.Text,
  'flTemp' : IDL.Float64,
  'rrTemp' : IDL.Float64,
  'tempUnit' : IDL.Text,
  'frTemp' : IDL.Float64,
  'timestamp' : IDL.Int,
  'rlPsi' : IDL.Float64,
  'rrPsi' : IDL.Float64,
  'rlTemp' : IDL.Float64,
});
export const WearEntry = IDL.Record({
  'id' : IDL.Text,
  'carId' : IDL.Text,
  'percentRemaining' : IDL.Float64,
  'installDate' : IDL.Text,
  'updatedAt' : IDL.Int,
  'treadDepthMm' : IDL.Float64,
  'notes' : IDL.Text,
  'wearType' : IDL.Text,
  'brand' : IDL.Text,
  'position' : IDL.Text,
  'lastChangedDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCar' : IDL.Func([Car], [], []),
  'createChecklistItem' : IDL.Func([ChecklistItem], [], []),
  'createEvent' : IDL.Func([Event], [], []),
  'createLapNote' : IDL.Func([LapNote], [], []),
  'createTireLogSession' : IDL.Func([TireLogSession], [], []),
  'createWearEntry' : IDL.Func([WearEntry], [], []),
  'deleteCar' : IDL.Func([IDL.Text], [], []),
  'deleteChecklistItem' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteLapNote' : IDL.Func([IDL.Text], [], []),
  'deleteTireLogSession' : IDL.Func([IDL.Text], [], []),
  'deleteWearEntry' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getChecklistItemsForEvent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChecklistItem)],
      ['query'],
    ),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getLapNotesForEvent' : IDL.Func([IDL.Text], [IDL.Vec(LapNote)], ['query']),
  'getTireLogSessionsForEvent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TireLogSession)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWearEntriesForCar' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WearEntry)],
      ['query'],
    ),
  'initDefaultChecklist' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleChecklistItem' : IDL.Func([IDL.Text], [], []),
  'updateCar' : IDL.Func([Car], [], []),
  'updateChecklistItem' : IDL.Func([ChecklistItem], [], []),
  'updateEvent' : IDL.Func([Event], [], []),
  'updateLapNote' : IDL.Func([LapNote], [], []),
  'updateTireLogSession' : IDL.Func([TireLogSession], [], []),
  'updateWearEntry' : IDL.Func([WearEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Car = IDL.Record({
    'id' : IDL.Text,
    'model' : IDL.Text,
    'nickname' : IDL.Text,
    'make' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Text,
    'eventId' : IDL.Text,
    'checked' : IDL.Bool,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'category' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'carId' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'location' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const LapNote = IDL.Record({
    'id' : IDL.Text,
    'eventId' : IDL.Text,
    'lapTime' : IDL.Text,
    'sessionName' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'lapNumber' : IDL.Nat,
  });
  const TireLogSession = IDL.Record({
    'id' : IDL.Text,
    'targetPsiMax' : IDL.Float64,
    'targetPsiMin' : IDL.Float64,
    'flPsi' : IDL.Float64,
    'frPsi' : IDL.Float64,
    'eventId' : IDL.Text,
    'sessionName' : IDL.Text,
    'flTemp' : IDL.Float64,
    'rrTemp' : IDL.Float64,
    'tempUnit' : IDL.Text,
    'frTemp' : IDL.Float64,
    'timestamp' : IDL.Int,
    'rlPsi' : IDL.Float64,
    'rrPsi' : IDL.Float64,
    'rlTemp' : IDL.Float64,
  });
  const WearEntry = IDL.Record({
    'id' : IDL.Text,
    'carId' : IDL.Text,
    'percentRemaining' : IDL.Float64,
    'installDate' : IDL.Text,
    'updatedAt' : IDL.Int,
    'treadDepthMm' : IDL.Float64,
    'notes' : IDL.Text,
    'wearType' : IDL.Text,
    'brand' : IDL.Text,
    'position' : IDL.Text,
    'lastChangedDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCar' : IDL.Func([Car], [], []),
    'createChecklistItem' : IDL.Func([ChecklistItem], [], []),
    'createEvent' : IDL.Func([Event], [], []),
    'createLapNote' : IDL.Func([LapNote], [], []),
    'createTireLogSession' : IDL.Func([TireLogSession], [], []),
    'createWearEntry' : IDL.Func([WearEntry], [], []),
    'deleteCar' : IDL.Func([IDL.Text], [], []),
    'deleteChecklistItem' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteLapNote' : IDL.Func([IDL.Text], [], []),
    'deleteTireLogSession' : IDL.Func([IDL.Text], [], []),
    'deleteWearEntry' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getChecklistItemsForEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChecklistItem)],
        ['query'],
      ),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getLapNotesForEvent' : IDL.Func([IDL.Text], [IDL.Vec(LapNote)], ['query']),
    'getTireLogSessionsForEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TireLogSession)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWearEntriesForCar' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WearEntry)],
        ['query'],
      ),
    'initDefaultChecklist' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleChecklistItem' : IDL.Func([IDL.Text], [], []),
    'updateCar' : IDL.Func([Car], [], []),
    'updateChecklistItem' : IDL.Func([ChecklistItem], [], []),
    'updateEvent' : IDL.Func([Event], [], []),
    'updateLapNote' : IDL.Func([LapNote], [], []),
    'updateTireLogSession' : IDL.Func([TireLogSession], [], []),
    'updateWearEntry' : IDL.Func([WearEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };