/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Car {
    id: string;
    model: string;
    nickname: string;
    make: string;
    createdAt: bigint;
    year: bigint;
    notes: string;
}
export interface ChecklistItem {
    id: string;
    eventId: string;
    checked: boolean;
    name: string;
    notes: string;
    category: string;
}
export interface Event {
    id: string;
    carId: string;
    date: string;
    name: string;
    createdAt: bigint;
    notes: string;
    location: string;
    eventType: string;
}
export interface WearEntry {
    id: string;
    carId: string;
    percentRemaining: number;
    installDate: string;
    updatedAt: bigint;
    treadDepthMm: number;
    notes: string;
    wearType: string;
    brand: string;
    position: string;
    lastChangedDate: string;
}
export interface LapNote {
    id: string;
    eventId: string;
    lapTime: string;
    sessionName: string;
    notes: string;
    timestamp: bigint;
    lapNumber: bigint;
}
export interface UserProfile {
    name: string;
}
export interface TireLogSession {
    id: string;
    targetPsiMax: number;
    targetPsiMin: number;
    flPsi: number;
    frPsi: number;
    eventId: string;
    sessionName: string;
    flTemp: number;
    rrTemp: number;
    tempUnit: string;
    frTemp: number;
    timestamp: bigint;
    rlPsi: number;
    rrPsi: number;
    rlTemp: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCar(car: Car): Promise<void>;
    createChecklistItem(item: ChecklistItem): Promise<void>;
    createEvent(event: Event): Promise<void>;
    createLapNote(note: LapNote): Promise<void>;
    createTireLogSession(session: TireLogSession): Promise<void>;
    createWearEntry(entry: WearEntry): Promise<void>;
    deleteCar(carId: string): Promise<void>;
    deleteChecklistItem(itemId: string): Promise<void>;
    deleteEvent(eventId: string): Promise<void>;
    deleteLapNote(noteId: string): Promise<void>;
    deleteTireLogSession(sessionId: string): Promise<void>;
    deleteWearEntry(entryId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCars(): Promise<Array<Car>>;
    getChecklistItemsForEvent(eventId: string): Promise<Array<ChecklistItem>>;
    getEvents(): Promise<Array<Event>>;
    getLapNotesForEvent(eventId: string): Promise<Array<LapNote>>;
    getTireLogSessionsForEvent(eventId: string): Promise<Array<TireLogSession>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWearEntriesForCar(carId: string): Promise<Array<WearEntry>>;
    initDefaultChecklist(eventId: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleChecklistItem(itemId: string): Promise<void>;
    updateCar(updatedCar: Car): Promise<void>;
    updateChecklistItem(updatedItem: ChecklistItem): Promise<void>;
    updateEvent(updatedEvent: Event): Promise<void>;
    updateLapNote(updatedNote: LapNote): Promise<void>;
    updateTireLogSession(updatedSession: TireLogSession): Promise<void>;
    updateWearEntry(updatedEntry: WearEntry): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCar(arg0: Car): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCar(arg0);
            return result;
        }
    }
    async createChecklistItem(arg0: ChecklistItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createChecklistItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChecklistItem(arg0);
            return result;
        }
    }
    async createEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0);
            return result;
        }
    }
    async createLapNote(arg0: LapNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLapNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLapNote(arg0);
            return result;
        }
    }
    async createTireLogSession(arg0: TireLogSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTireLogSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTireLogSession(arg0);
            return result;
        }
    }
    async createWearEntry(arg0: WearEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWearEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWearEntry(arg0);
            return result;
        }
    }
    async deleteCar(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCar(arg0);
            return result;
        }
    }
    async deleteChecklistItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChecklistItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChecklistItem(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteLapNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLapNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLapNote(arg0);
            return result;
        }
    }
    async deleteTireLogSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTireLogSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTireLogSession(arg0);
            return result;
        }
    }
    async deleteWearEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWearEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWearEntry(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCars(): Promise<Array<Car>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCars();
            return result;
        }
    }
    async getChecklistItemsForEvent(arg0: string): Promise<Array<ChecklistItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChecklistItemsForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChecklistItemsForEvent(arg0);
            return result;
        }
    }
    async getEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents();
            return result;
        }
    }
    async getLapNotesForEvent(arg0: string): Promise<Array<LapNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLapNotesForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLapNotesForEvent(arg0);
            return result;
        }
    }
    async getTireLogSessionsForEvent(arg0: string): Promise<Array<TireLogSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTireLogSessionsForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTireLogSessionsForEvent(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWearEntriesForCar(arg0: string): Promise<Array<WearEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWearEntriesForCar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWearEntriesForCar(arg0);
            return result;
        }
    }
    async initDefaultChecklist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initDefaultChecklist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initDefaultChecklist(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleChecklistItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleChecklistItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleChecklistItem(arg0);
            return result;
        }
    }
    async updateCar(arg0: Car): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCar(arg0);
            return result;
        }
    }
    async updateChecklistItem(arg0: ChecklistItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChecklistItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChecklistItem(arg0);
            return result;
        }
    }
    async updateEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0);
            return result;
        }
    }
    async updateLapNote(arg0: LapNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLapNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLapNote(arg0);
            return result;
        }
    }
    async updateTireLogSession(arg0: TireLogSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTireLogSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTireLogSession(arg0);
            return result;
        }
    }
    async updateWearEntry(arg0: WearEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWearEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWearEntry(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
